name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'vRESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug fixes'
    labels:
      - 'fix'
      - 'bugifx'
      - 'bug'
  - title: 'Maintenance'
    labels: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    lables:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes


  $CHANGES
