---
name: module3_task0
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the help target
        uses: actions/checkout@v3
      - name: cd to directory containing symlink
        run: |
          cd module3_task0/
          make help
