---
name: module3_task3
on:
  push:
    branches:
      - main
  schedule:
    # * is special character quote it!
    # trigger the workflow every day at 5:30 and 17:30 UTC
    - cron: '30 10 * * *'

jobs:
  module3_task2_make_build_workflow:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the build target
        uses: actions/checkout@v3
      - name: Setting hugo and build
        run: |
          cd module3_task3
          ./setup.sh
      - name: lint
        run: |
          cd module3_task3
          make lint
      - name: build
        run: |
          cd module3_task3
          make build
      - name: post
        run: |
          cd module3_task3
          make POST_TITLE=Test POST_NAME='TestSuccess' post
      - name: integration testing
        run: |
          cd module3_task3
          make validate
          make integration-tests
          make unit-tests
          make package
          make clean
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 1.0.0
          files: |
            module3_task3/awesome-website.zip
            module3_task3/DEPLOY.md
      - name: build the archive
        # if none of previous steps have failed, success returns true
        if: ${{ success()}}
        uses: actions/upload-artifact@v3
        with:
          name: build package
          path: module3_task3/awesome-website.zip
