---
name: module3_task1
on:
  push:
    branches:
      - main
  schedule:
    # * is special character quote it!
    # trigger the workflow every day at 5:30 and 17:30 UTC
    - cron: '30 10 * * *'

jobs:
  module3_task1_make_build_workflow:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the build target
        uses: actions/checkout@v3
      - name: running
        run: |
          cd module3_task1
          ./setup.sh
      - name: lint
        run: |
          cd module3_task1
          make lint
      - name: build
        run: |
          cd module3_task1
          make build
      - name: Unit testing
        run: |
          cd module3_task1
          make unit-tests
      - name: integration testing
        run: |
          cd module3_task1
